### ISSUE TITLE
Komponent Nawigacja

### ISSUE THREAD

**Issue by lagdush** [piotr-bocian/Projekt-5#2]
Ikonka, tytuł, menu, zaloguj się/ zarejestruj

**Comment by piotr-bocian** [comment]
Na szybko parę rzeczy: 
- Logowanie i rejestracja powinny być osobnymi odnośnikami.
- W założeniu kliknięcie na logo powinno przeładowywać stronę więc proponuję spiąć obrazek i napis w jeden komponent.
- Postaraj się ustawić dropdown na hover a nie na kliknięcie - bardziej intuicyjne imo.
- Przydałby się jakiś subtelny hover dla ikon - najlepiej taki sam jak w elementach nawigacji ale można pokombinować.
- Background-color dla active dziwnie się zachowuje (po prostu zmienia się tło nie tego elementu co trzeba)
